services:
  - type: web
    name: bot-controle-gastos
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000